x-dev-env: &dev-env
  env_file:
    - ./.env.dev

services:
  nginx:
    <<: *dev-env

  litellm:
    <<: *dev-env

  portainer:
    <<: *dev-env

  mlflow:
    <<: *dev-env

  mimir:
    <<: *dev-env

  loki:
    <<: *dev-env

  grafana:
    <<: *dev-env

  prometheus:
    <<: *dev-env

  minio:
    <<: *dev-env

  postgres:
    <<: *dev-env