include:
  - compose.yaml

services:
  litellm:
    env_file:
      - ./.env.prod

  grafana:
    env_file:
      - ./.env.prod

  prometheus:
    env_file:
      - ./.env.prod

  minio:
    env_file:
      - ./.env
      - ./.env.prod

  postgres:
    env_file:
      - ./.env.prod

  nginx:
    env_file:
      - ./.env.prod