x-prod-env: &prod-env
  env_file:
    - ./.env.prod

services:
  nginx:
    <<: *prod-env

  litellm:
    <<: *prod-env

  portainer:
    <<: *prod-env

  mlflow:
    <<: *prod-env

  mimir:
    <<: *prod-env

  loki:
    <<: *prod-env

  grafana:
    <<: *prod-env

  prometheus:
    <<: *prod-env

  minio:
    <<: *prod-env

  postgres:
    <<: *prod-env