include:
  # - ./services/litellm/compose.yaml
  # - ./services/mlflow/compose.yaml
  - ./services/minio/compose.yaml
  # - ./services/grafana/compose.yaml
  # - ./services/prometheus/compose.yaml
  # - ./services/portainer/compose.yaml
  # - ./services/postgres/compose.yaml
  # - ./services/nginx/compose.yaml