services:
  tempo:
    image: grafana/tempo:${TEMPO_VERSION}
    container_name: tempo
    env_file:
      - path: ../../${ENV_FILE:-.env}
        required: true
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo
    command:
      - -config.file=/etc/tempo/tempo.yaml
      - -config.expand-env=true

volumes:
  tempo_data:
    name: tempo_data
