services:
  tempo:
    image: grafana/tempo:${TEMPO_VERSION}
    container_name: tempo
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo
    command:
      - -config.file=/etc/tempo/tempo.yaml
      - -config.expand-env=true

volumes:
  tempo_data:
    name: tempo_data
