services:
  alloy:
    image: grafana/alloy:${ALLOY_VERSION}
    container_name: alloy
    env_file:
      - ../../.env
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/etc/alloy/config.yaml:ro
    command:
      - --config.file=/etc/alloy/config.yaml