services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:${LITTELM_VERSION}
    container_name: litellm
    env_file:
      - path: ../../${ENV_FILE:-.env}
        required: true
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - postgres
    command: >
      --config /app/config.yaml
