services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:${LITTELM_VERSION}
    container_name: litellm
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_DATABASE_URL: ${LITELLM_DATABASE_URL}
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - postgres
    command: >
      --config /app/config.yaml
