services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    env_file:
      - path: ../../${ENV_FILE:-.env}
        required: true
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.core.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

volumes:
  prometheus_data:
    name: prometheus_data
