services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    env_file:
      - ../.env.dev
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    name: grafana_data