services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki
    env_file:
      - path: ../../${ENV_FILE:-.env}
        required: true
    volumes:
      - loki_data:/loki
      - ./config.yaml:/etc/loki/config.yaml:ro
    command:
      - --config.file=/etc/loki/config.yaml
      - --config.expand-env=true
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  loki_data:
    name: loki_data