services:
  mimir:
    image: grafana/mimir:${MIMIR_VERSION}
    container_name: mimir
    env_file:
      - path: ../../${ENV_FILE:-.env}
        required: true
    volumes:
      - ./config.yaml:/etc/mimir/config.yaml:ro
      - mimir_data:/data
    command:
      - --config.file=/etc/mimir/config.yaml
      - --config.expand-env=true
    depends_on:
      minio:
        condition: service_healthy

volumes:
  mimir_data:
    name: mimir_data