services:
  mimir:
    image: grafana/mimir:${MIMIR_VERSION}
    container_name: mimir
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./config.yaml:/etc/mimir/config.yaml:ro
      - mimir_data:/data
    command:
      - --config.file=/etc/mimir/config.yaml
      - --config.expand-env=true
    depends_on:
      minio:
        condition: service_healthy

volumes:
  mimir_data:
    name: mimir_data